"use client";

import { Badge } from "@/components/ui/badge";

export function Footer() {
  return (
    <footer className="bg-primary dark:bg-background text-primary-foreground dark:text-muted-foreground py-8 border-t border-primary/50 dark:border-border">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 text-center">
        <p className="text-sm">Generated by Z.ai | July 2026 | SMP v5.1 Protocol</p>
        <p className="text-xs mt-2 text-white/50 dark:text-muted-foreground/50">Comprehensive Proxy Analysis & Installation Guide — Interactive Web Edition</p>
        <div className="flex items-center justify-center gap-4 mt-4 flex-wrap">
          <Badge variant="outline" className="text-xs border-white/30 dark:border-border text-white/60 dark:text-muted-foreground">Next.js 16</Badge>
          <Badge variant="outline" className="text-xs border-white/30 dark:border-border text-white/60 dark:text-muted-foreground">Framer Motion</Badge>
          <Badge variant="outline" className="text-xs border-white/30 dark:border-border text-white/60 dark:text-muted-foreground">shadcn/ui</Badge>
          <Badge variant="outline" className="text-xs border-white/30 dark:border-border text-white/60 dark:text-muted-foreground">Tailwind CSS 4</Badge>
          <Badge variant="outline" className="text-xs border-white/30 dark:border-border text-white/60 dark:text-muted-foreground">WebSocket</Badge>
        </div>
      </div>
    </footer>
  );
}
